### PR TITLE
Fix parallel request processing for RemoteDataSource

### LINKED ISSUE #31: Parallel execution of RemoteDataSource does not work due to httplib Client lock
Currently, all workers for a RemoteDataSource share the same httplib Client. However, it is not possible to run parallel requests through one socket, so the parallelization is effectively disabled.

### PR DESCRIPTION
**Pull request by josephbirkner**
Changes in this PR:

* RemoteDataSource has multiple httplib clients, fixes #31 
* Extend status page: Now shows cache statistics.
* Allow access to `TileLayerStream::Reader` field dict offsets: Needed by erdblick to set the maxKnownFieldIds for the tiles request. If this optional dict is set in the request, the tile layer stream will not contain field id mapping info that has already been sent and is already known to the client (erdblick).

### CODE REVIEW

File: libs/http-datasource/src/datasource-client.cpp [hunk 1]
```diff
@@ -30,8 +35,11 @@ void RemoteDataSource::fill(const TileFeatureLayer::Ptr& featureTile)
 TileFeatureLayer::Ptr
 RemoteDataSource::get(const MapTileKey& k, Cache::Ptr& cache, const DataSourceInfo& info)
 {
+    // Round-robin usage of http clients to facilitate parallel requests
+    auto& client = httpClients_[(nextClient_++) % httpClients_.size()];
+
     // Send a GET tile request
-    auto tileResponse = httpClient_.Get(stx::format(
+    auto tileResponse = client.Get(stx::format(
```
Comment (johannes-wolf) [inline libs/http-datasource/src/datasource-client.cpp:42]: How does this work if the client is already in use by another invocation of `::get`, on another thread?

Comment (josephbirkner) [reply libs/http-datasource/src/datasource-client.cpp:42]: The httplib client is internally thread-safe, so it will just wait - this means that the data source server will really never get more parallel requests than its `maxParallelRequests` value indicates.

Comment (johannes-wolf) [reply libs/http-datasource/src/datasource-client.cpp:42]: Then this is still suboptimal because if the selected client is busy, but the next one would be free, this will still block. But I think that is ok(?).

Comment (josephbirkner) [reply libs/http-datasource/src/datasource-client.cpp:42]: Yes, I think so. I like the simple round-robin :)

**Review by johannes-wolf — APPROVED** [review]
LGTM.

**Review by johannes-wolf — APPROVED** [review]
Did you change anything besides the full stops (after my first review)?

**Comment by josephbirkner** [comment]
> Did you change anything besides the full stops (after my first review)?

Nope 🙂
